In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.random.rand(4,4)

array([[0.19783858, 0.29596939, 0.10160141, 0.69950869],
       [0.35989032, 0.75676731, 0.35088749, 0.92013401],
       [0.16217526, 0.58301984, 0.74400001, 0.56602745],
       [0.59358439, 0.94465375, 0.00332906, 0.04488755]])

In [12]:
np.random.rand(5)

array([0.40341941, 0.29961347, 0.78613397, 0.36611109, 0.78812641])

In [14]:
np.random.randint(1,100,10)

array([19, 57, 63, 95, 89, 33, 38, 30, 52, 65])

In [15]:
from numpy.random import randint

In [20]:
randint(2,10)

5

## indexing

In [24]:
arr = np.arange(0,10)

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[4:6]

array([4, 5])